# Generated by Django 3.2.5 on 2021-07-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Altura')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Peso')),
                ('image', models.URLField(verbose_name='Url Image')),
                ('hp', models.PositiveSmallIntegerField(verbose_name='Vida')),
                ('attack', models.PositiveSmallIntegerField(verbose_name='Ataque')),
                ('defense', models.PositiveSmallIntegerField(verbose_name='Defensa')),
                ('special_attack', models.PositiveSmallIntegerField(verbose_name='Ataque Especial')),
                ('special_defense', models.PositiveSmallIntegerField(verbose_name='Defensa Especial')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='Velocidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type_ids', models.ManyToManyField(to='pokemon.Types')),
            ],
        ),
    ]
